version: '3.2'
services:

    dbmyfinance:
       image: postgres
       restart: always
       volumes:
         - db-myfinance:/var/lib/postgresql/data
       ports:
         - 5432:5432
       environment:
         POSTGRES_USER: myfinance
         POSTGRES_PASSWORD: password
       logging:
         driver: "json-file"
         options:
           max-size: "10m"
           max-file: "10"

    #admin: password: password
    rpi-keycloak:
        restart: always
        privileged: true
        volumes:
          - db-keycloak:/data
        ports:
            - '8180:8080'
            - '9990:9990'
        image: ruifigueiredo/rpi-keycloak
        logging:
          driver: "json-file"
          options:
            max-size: "10m"
            max-file: "10"

    myfinance-backend:
       image: myfinance-backend:0.0.4
       restart: always
       ports:
         - '3000:3000'
         - '8181:8181'
       environment:
         ENV_API_USER: patrick
         ENV_API_PASS: patrick
         ENV_MAIL_ADRE: mail.sender@gmail.com
         ENV_MAIL_PASS: password
         ENV_MAIL_TO: mail.send_notification@gmail.com
         ENV_DB_USER: dbuser
         ENV_DB_HOST: dbhost
         ENV_DB_DATABASE: dbdatabase
         ENV_DB_PASSWORD: dbpassword
         ENV_DB_PORT: dbport
       logging:
         driver: "json-file"
         options:
           max-size: "10m"
           max-file: "10"

    myfinance-frontend:
       image: myfinance-frontend:0.0.3
       restart: always
       ports:
         - '8081:80'
       logging:
         driver: "json-file"
         options:
           max-size: "10m"
           max-file: "10"


volumes:
  db-myfinance:
  db-keycloak:

